version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: smartcampus-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=smartcampus

  backend:
    build: ./backend
    container_name: smartcampus-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/smartcampus
      - JWT_SECRET=supersecret
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: smartcampus-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo-data:

